### ISSUE TITLE
library not working on heroku

### ISSUE THREAD

**Issue by jbhatab** [gutschilla/elixir-pdf-generator#17]
This may just be me doing things incorrectly on heroku but I thought I'd make an issue since other coders will probably hit this. I added wkhtmltopdf and pdftk buildpacks to my heroku setup,

https://github.com/HashNuke/heroku-buildpack-elixir
https://github.com/gjaldon/phoenix-static-buildpack
https://github.com/dscout/wkhtmltopdf-buildpack.git
https://github.com/fxtentacle/heroku-pdftk-buildpack.git

The first two are standard phoenix+elixir buildpacks which work fine. For some reason though this is still failing while using heroku. It doesn't seem to report an error in the logger but it was my PDFgenerator branch that broke heroku. Any ideas on this?

**Comment by jbhatab** [comment]
Ended up getting it to work by reordering the buildpacks. This was the order that worked.

https://github.com/fxtentacle/heroku-pdftk-buildpack.git
https://github.com/dscout/wkhtmltopdf-buildpack.git
https://github.com/HashNuke/heroku-buildpack-elixir
https://github.com/gjaldon/phoenix-static-buildpack

**Comment by gutschilla** [comment]
@jbhatab Hi, sorry for my late reply. Would you mind creating a PR that includes this order in README in case anyone else wants to get this running on Heroku?

**Comment by lypborges** [comment]
@jbhatab I make this order but how do you set the wkhtmltopdf path on config? I couldn't get every thing working. Can you share how do you set your app to run wkhtmltopdf on another buildpack?

**Comment by jbhatab** [comment]
@gutschilla Oh sorry I missed this. Yeah I can make a PR.

**Comment by lypborges** [comment]
I had to add for prod.exs
```elixir
config :pdf_generator,
    wkhtml_path:    "bin/wkhtmltopdf"
```
and worked. 
The font size it's much bigger that was in dev (local, mac).I'm not sure if the problem is on local or production environment,  but I'll figure out. ;)

**Comment by gutschilla** [comment]
@lypborges Great you found that. It's documented here already: https://github.com/gutschilla/elixir-pdf-generator#options-and-configuration. I should possibly add a "getting started" section. Thing is, I work on Linux and istalled wkhtmltopdf just from the package repository so it was availableon path and this module attempts to find it there first if not configured otherwise.

For the font sizes: Are you sure all fints you used are installed? I guess Heroku is not using Macs to power their cloud so their images could simply not include any fonts. Especially not Apple's won ones. 

If I need to use fonts in a PDF I do reference them directly in the HTML's CSS statements, either by referencing the WOF (or TTF) files or using a webfont.

**Comment by jbhatab** [comment]
@lypborges I had to do a lot of trial and error to find the right settings for prod vs local. Here's my settings if this helps.

```

**Comment by jbhatab** [comment]
@gutschilla opened up a PR. https://github.com/gutschilla/elixir-pdf-generator/pull/21. Might help some people. Let me know what you think.

**Comment by CrowdHailer** [comment]
Just opened a new issue #25 because I cannot get these instructions to work for me
