### ISSUE TITLE
elixir-pdf-generator fails due to Porcelain error when packaged in distillery using hot code upgrading

### ISSUE THREAD

**Issue by samginn** [gutschilla/elixir-pdf-generator#33]
When I perform a hot code upgrade on a running server, the elixir-pdf-generator fails whenever it is called with the following error:

```(Porcelain.UsageError) Looks like the :porcelain app is not running. Make sure you've added :porcelain to the list of applications in your mix.exs.```

I've added :porcelain to mix.exs as well as added it to ```rel/config.exs``` under applications, but neither solve the problem. Manually restarting the server works just fine and PDFGenerator will work correctly without any porcelain errors. However, whenever I perform a hot code upgrade, it will generate this error.

**Comment by gutschilla** [comment]
Uh-oh. I quite honestly never tested for that scenario :-/ - Even though your error very much looks like if there was a configuration error. Are you using distillery?

**Comment by samginn** [comment]
Yep, using Distillery for the release.

**Comment by gutschilla** [comment]
Lemme dig into this. This my take a while, though. Can't promise a sucess. Can you come up with an example. A link to your repo would be helpful.

**Comment by darksheik** [comment]
This issue is present in the `porcelain` Repo:  https://github.com/alco/porcelain/issues/41

I discovered the basic issue which is that this call throws the error after a hot upgrade:

```
Application.fetch_env(:porcelain, :driver_internal)
```

If you manually call:

```
Porcelain.Init.init()
```

It solves the problem as a workaround within your app.  I have been playing around with trying to get a hot upgrade to work on a fork, but haven't been successful so far.

**Comment by gutschilla** [comment]
Hmmm... For now I fear I will have to add a warning to the README indicating that hot code upgrades don't work with elixir-pdf-generator.

**Comment by ijunaid8989** [comment]
@darksheik Are you still solving this in the same way?

**Comment by ijunaid8989** [comment]
@darksheik Hello? Is that ever worked for you? the above reinit of Porcelain? It didnt work for me not even once. Even config_change not even called.

**Comment by gutschilla** [comment]
@ijunaid8989 PdfGenerator will be moving away from Porcelain due to these issues and it being generally not maintained any more. I plan to come up with a plain `Port` implementation – see https://github.com/gutschilla/elixir-pdf-generator/issues/44

Unfortunately this won't happen until end of September. (my day job takes its toll)

**Comment by gutschilla** [comment]
This has been addressed in https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.5.0
